site_name: OWASP Mobile Application Security
repo_url: https://github.com/OWASP/owasp-mastg
repo_name: OWASP/owasp-mastg
# use_directory_urls: false # only set for mkdocs build

# https://www.mkdocs.org/user-guide/configuration/#validation
# due to our use of mkdocs-awesome-pages-plugin, we need to ignore absolute links for nav
validation:
  nav:
    absolute_links: ignore

nav:
  - Home: index.md
 
  - MASTG:
      - Tests:
        - MASTG/tests/index.md
    

copyright: |
  <div style="float: left; padding-right: 1em;">
    <a href="https://www.owasp.org"><img src="https://github.com/OWASP/owasp-mastg/blob/master/Document/Images/OWASP_logo_white.png?raw=true" width="100px" /></a>
  </div>
  <span style="font-size: smaller">
    &#169; OWASP Foundation 2025. This work is licensed under 
    <a href="https://creativecommons.org/licenses/by/4.0">CC-BY-4.0</a>. For any reuse or distribution, you must make clear to others the license terms of this work.
  </span><br><span style="font-size: smaller">OWASP &#174; is a registered trademark of the OWASP Foundation, Inc.</span> <span style="font-size: smaller">This website uses cookies to analyze our traffic and only share that information with our analytics partners. <a href="https://github.com/OWASP/owasp-mastg/blob/master/about_cookies.md">Learn more</a>.</span>
  <div style="color: #6a6868; font-size: smaller"><span>Made with</span> <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>  | <i>Website and covers designed by Carlos Holguera.</i></div>

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_circle.png
  favicon: assets/logo_circle.png
  icon:
    repo: fontawesome/brands/github
    tag:
      android: material/android
      ios: material/apple
      p: material/eye-circle-outline
      l1: material/circle
      l2: material/circle-multiple-outline
      r: material/circle-double
      placeholder: material/pencil-plus
      update-pending: material/information-outline
      deprecated: material/trash-can
      new: material/alert-decagram
      tool: octicons/tools-24
      test: octicons/codescan-checkmark-24
      app: octicons/code-square-24
      demo: material/flask-outline
      tech: material/magic-staff # fontawesome/solid/wand-magic-sparkles
      best: material/shield-check
      maswe: octicons/shield-24
      masvs: simple/owasp
  features:
    - search.suggest
    - search.share
    # - toc.integrate
    - navigation.instant
    # - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.action.edit

  palette:
    # - primary: #499FFF 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/v/dt/dt-2.3.2/b-3.2.3/sp-2.3.3/sp-2.3.3/rg-1.5.1/datatables.min.css

extra_javascript:
  - javascripts/external_links.js
  - https://code.jquery.com/jquery-3.5.1.js
  - https://cdn.datatables.net/v/dt/dt-2.3.2/b-3.2.3/sp-2.3.3/sl-3.0.1/rg-1.5.1/datatables.min.js

  # - js/init-searchpanes.js
  - javascripts/datatables.js
plugins:
  # Uses https://github.com/mkdocs/mkdocs-redirects getting the redirects map from src/scripts/generate_redirects.py
  - search
  - awesome-pages
  # - privacy
  # - offline
  - blog:
  # https://squidfunk.github.io/mkdocs-material/plugins/blog/
      blog_dir: news
      pagination_per_page: 10
      post_excerpt_max_authors: 2
  - tags
      # tags_file: tags.md # TODO: bug in mkdocs? dynamic tags from hooks not appearing in tags.md
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: false
      base_path:
        - !relative # allows to include snippets from the same folder
        # - docs/MASTG/ # alternative to include snippets from specific folders
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

hooks:
  - docs/hooks/replace_snippets.py
  - docs/hooks/update_titles.py
  - docs/hooks/add-tags.py
  - docs/hooks/add-cross-references.py
  - docs/hooks/edit_button_uri.py
  - docs/hooks/resolve_references.py
  - docs/hooks/create_dynamic_tables.py
  - docs/hooks/update_git_info.py
  - docs/hooks/add-checklists-banner.py
  - docs/hooks/maswe-beta-banner.py

extra:
  generator: false # removed but recreated in copyright above
  analytics:
    provider: google
    property: G-KWZRJV0S4P
  social:
    - icon: fontawesome/brands/slack
      link: https://owasp.slack.com/archives/C1M6ZVC6S
    - icon: fontawesome/brands/bluesky 
      link: https://bsky.app/profile/owasp-mas.bsky.social
    - icon: fontawesome/brands/mastodon 
      link: https://infosec.exchange/@OWASP_MAS
    - icon: fontawesome/brands/github
      link: https://github.com/OWASP/owasp-mastg/discussions
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:carlos.holguera@owasp.org
    #   name: Carlos Holguera
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:sven.schleier@owasp.org
    #   name: Sven Schleier
  tags:
    android: android
    ios: ios
    P: p
    L1: l1
    L2: l2
    R: r
    placeholder: placeholder
    update-pending: update-pending
    deprecated: deprecated
    new: new
    tool: tool
    test: test
    app: app
    demo: demo
    tech: tech
    maswe: maswe
    masvs: masvs
    best: best
  status:
    placeholder: This page is a placeholder.
    deprecated: This page is deprecated.
    new: This page is new!
    update-pending: This page is pending an update.
